import * as THREE from './vendor/package/build/three.module.js';
import {cellPosition,canWalk,movePlayer} from './navigation.mjs';
const $=id=>document.getElementById(id),stage=$('stage');
try{await start();}catch(error){$('hint').textContent='No se pudo iniciar 3D. Prueba un navegador con WebGL 2.';console.error(error);}
async function start(){
const response=await fetch('./world.json');if(!response.ok)throw Error('Mapa no disponible');const data=await response.json();
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'low-power'});renderer.setPixelRatio(1);renderer.setSize(640,360,false);stage.prepend(renderer.domElement);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,170),ambient=new THREE.HemisphereLight(0xe4efff,0x445430,2.2),sun=new THREE.DirectionalLight(0xffedbe,2.3);sun.position.set(-15,30,10);scene.add(ambient,sun);
let town=new THREE.Group(),roomId='valpo',room,cameraMode=0,angle=0,phase=0,walk=0;scene.add(town);const lamps=[],people=[],doors=[],keys=new Set(),meshes=[];const materials=new Map();
const material=color=>{if(!materials.has(color))materials.set(color,new THREE.MeshLambertMaterial({color,flatShading:true}));return materials.get(color);};
function box(parent,x,y,z,w,h,d,color){const geometry=new THREE.BoxGeometry(w,h,d),mesh=new THREE.Mesh(geometry,material(color));mesh.position.set(x,y,z);parent.add(mesh);meshes.push(mesh);return mesh;}
function cone(parent,x,y,z,r,h,color,sides=5){const mesh=new THREE.Mesh(new THREE.ConeGeometry(r,h,sides),material(color));mesh.position.set(x,y,z);parent.add(mesh);meshes.push(mesh);return mesh;}
function sign(parent,text,x,y,z,width=6,color='#193c40'){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const c=canvas.getContext('2d');c.fillStyle='#d4b56d';c.fillRect(0,0,256,64);c.fillStyle=color;c.fillRect(4,4,248,56);c.fillStyle='#fff0c5';c.font='bold 25px monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(text,128,33,238);const tex=new THREE.CanvasTexture(canvas);tex.magFilter=THREE.NearestFilter;tex.minFilter=THREE.LinearFilter;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,width/4),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));mesh.position.set(x,y,z);parent.add(mesh);meshes.push(mesh);return mesh;}
function person(look){const root=new THREE.Group(),c=look.c||data.hero.c;box(root,0,1.15,0,.65,.8,.4,c.shirt);box(root,0,1.35,-.24,.6,.7,.09,c.cape||c.shirtD);box(root,0,1.88,0,.55,.55,.5,c.skin);box(root,0,2.17,0,.6,.2,.53,c.hair);if(c.hat&&/cap|beanie|wizard/.test(look.style)){box(root,0,2.3,0,.68,.25,.6,c.hat);box(root,0,2.19,.33,.68,.08,.32,c.hatD||c.hat);}box(root,-.12,1.94,.258,.07,.07,.02,'#252327');box(root,.12,1.94,.258,.07,.07,.02,'#252327');box(root,0,1.73,.285,.12,.1,.07,c.skin);box(root,0,.89,.21,.65,.12,.06,c.belt||'#614a26');const limbs=[];for(const side of [-1,1]){const arm=new THREE.Group();arm.position.set(side*.43,1.5,0);box(arm,0,-.3,0,.22,.6,.25,c.shirt);box(arm,0,-.68,0,.22,.19,.25,c.skin);root.add(arm);const leg=new THREE.Group();leg.position.set(side*.2,.79,0);box(leg,0,-.32,0,.25,.65,.28,c.pants);box(leg,0,-.71,.07,.3,.18,.44,c.shoe);root.add(leg);limbs.push(arm,leg);}root.userData.limbs=limbs;return root;}
const hero=person(data.hero);scene.add(hero);
function tree(x,z){box(town,x,1.05,z,.5,2.1,.5,'#77513c');cone(town,x,2.7,z,1.6,3,'#426b42');cone(town,x,3.8,z,1.15,2.7,'#658445');}
function lamp(x,z){box(town,x,1.6,z,.13,3.2,.13,'#243338');box(town,x,3.15,z,.65,.7,.65,'#e4c481');cone(town,x,3.7,z,.55,.45,'#26373a',4);const glow=new THREE.PointLight(0xffbd65,0,6,2);glow.position.set(x,3,z);town.add(glow);lamps.push(glow);}
function rebuild(id){town.traverse(mesh=>{if(mesh.isMesh){mesh.geometry.dispose();if(mesh.material.map){mesh.material.map.dispose();mesh.material.dispose();}}});meshes.length=0;scene.remove(town);town=new THREE.Group();scene.add(town);lamps.length=people.length=doors.length=0;roomId=id;room=data.rooms[id];const indoor=id!=='valpo';
box(town,0,-.45,0,45,.7,30,indoor?'#302937':'#67663c');
for(let y=0;y<10;y++)for(let x=0;x<15;x++){const p=cellPosition(x,y),tile=room.map[y][x];let color=indoor?'#7b665d':((x*13+y*7)%3?'#849555':'#7d8e4e');if('=,'.includes(tile))color='#bea77b';if('~JL'.includes(tile))color='#487d9c';box(town,p.x,-.06,p.z,3,.15,3,color);if(tile==='T')tree(p.x,p.z);if(indoor&&'wk'.includes(tile))box(town,p.x,1.4,p.z,x===0||x===14?.5:3,2.8,x===0||x===14?3:.5,'#78533d');if(indoor&&tile==='t'){box(town,p.x,.9,p.z,2.8,.18,1.65,'#9c623e');for(const a of [-1,1])box(town,p.x+a, .45,p.z,.18,.9,.6,'#573f31');for(const a of [-.8,0,.8]){box(town,p.x+a,1.02,p.z,.48,.04,.65,'#e7d6af');box(town,p.x+a,1.05,p.z,.3,.02,.42,['#a33f3c','#2e7095','#466e3f'][Math.round(a/.8)+1]);}}}
if(!indoor){for(let y=0;y<10;y++){let x=0;while(x<15){if(room.map[y][x]!=='W'){x++;continue;}const left=x;while(x<15&&'WD'.includes(room.map[y][x]))x++;const width=x-left,center=cellPosition(left+(width-1)/2,y),roofColor=left<6?(y<5?'#77364a':'#8a5c3f'):(y<5?'#63734c':'#3f5e82');box(town,center.x,1.65,center.z-1.3,width*3,3.3,5.6,'#d2bd8d');const w=width*3/2+.35,d=3.15;const v=[[-w,0,d],[w,0,d],[0,2,d],[-w,0,-d],[w,0,-d],[0,2,-d]],indices=[0,1,2,4,3,5,0,2,5,0,5,3,2,1,4,2,4,5];const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(indices.flatMap(i=>v[i]),3));geo.computeVertexNormals();const roof=new THREE.Mesh(geo,material(roofColor));roof.position.set(center.x,3.4,center.z-1.3);town.add(roof);meshes.push(roof);for(let wx=left;wx<x;wx++){const wp=cellPosition(wx,y);if(room.map[y][wx]==='D'){box(town,wp.x,1.18,wp.z+1.54,1.55,2.35,.13,'#684631');box(town,wp.x+.45,1.12,wp.z+1.65,.12,.12,.12,'#e8b458');}else{box(town,wp.x,1.85,wp.z+1.54,1.1,1.15,.12,'#415d71');box(town,wp.x,1.85,wp.z+1.64,.1,1.2,.08,'#ebd5a2');}}const label=(room.plaques||[]).find(p=>Math.abs(p[2]/16-(y-1))<1.6&&Math.abs(p[1]/16-(left+width/2))<width/2);if(label)sign(town,label[0],center.x,2.85,center.z+1.67,Math.min(width*2.5,8),label[3]);}}
for(const p of room.props||[]){const q=cellPosition(p.x,p.y);if(p.k==='farol')lamp(q.x,q.z);if(p.k==='cerezo')tree(q.x,q.z);if(p.k==='barril')box(town,q.x,.65,q.z,1,1.3,1,'#8f633a');if(p.k==='parra'){box(town,q.x,.6,q.z,.12,1.2,.12,'#6c513c');box(town,q.x,1.2,q.z,2.4,.7,1.5,'#556e3e');}if(p.k==='fogata'){cone(town,q.x,.4,q.z,.4,.85,'#ff9639');const light=new THREE.PointLight(0xff9340,4,5);light.position.set(q.x,1,q.z);town.add(light);}}
}else{for(const p of room.props||[]){const q=cellPosition(p.x+(p.w||1)/2-.5,p.y);if(p.k==='mesaCartas'||p.k==='mostrador'){const w=(p.w||3)*3-.5;box(town,q.x,1,q.z,w,.25,2.1,p.k==='mostrador'?'#87583e':'#466979');for(const a of [-1,1])box(town,q.x+a*(w/2-.3),.5,q.z,.3,1,.8,'#4e3a2b');if(p.k==='mesaCartas')for(const a of [-2,0,2]){box(town,q.x+a,1.15,q.z,.75,.04,1,'#e0d1ac');box(town,q.x+a,1.18,q.z,.52,.03,.65,a<0?'#b24d3e':'#304774');}else sign(town,p.label||'TCG',q.x,2.2,q.z,4);}}sign(town,'LIGA DE CURICÓ',0,3,-11,9,'#3b334b');sign(town,'STANDINGS',8,2.9,-11,4,'#4f3b26');lamp(-18,-9);lamp(18,-9);}
for(const [key,target] of Object.entries(room.doors||{})){const [x,y]=key.split(',').map(Number),q=cellPosition(x,y);doors.push({...q,target});}
for(const npc of room.npcs||[]){const p=cellPosition(npc.x/16-.2,npc.y/16-.5),body=person(npc.look);body.position.set(p.x,0,p.z);town.add(body);people.push({body,name:npc.look.n});}
const spawn=indoor?cellPosition(7,7):cellPosition(7,7);hero.position.set(spawn.x,0,spawn.z);hero.rotation.y=Math.PI;hero.userData.limbs.forEach(l=>l.rotation.x=0);$('tag').textContent=room.name+' · VERSIÓN 3D';$('visit').textContent=indoor?'Volver a Curicó':'Visitar tienda TCG';setLight();resize();}
function setLight(){const palettes=[['#a7c6c9',2.2,2.3],['#bd9c92',1.5,1.5],['#172b46',.65,.45]];const p=palettes[phase];scene.background=new THREE.Color(p[0]);scene.fog=new THREE.Fog(p[0],100,180);ambient.intensity=p[1];sun.intensity=p[2];sun.color.set(phase===1?'#ffb574':'#ffedbe');lamps.forEach(l=>l.intensity=phase===2?8:phase===1?3:0);$('light').textContent='Luz: '+['día','atardecer','noche'][phase];}
function nearby(){const d=doors.find(d=>Math.hypot(hero.position.x-d.x,hero.position.z-d.z)<3.5);if(d)return {door:d};const n=people.find(n=>n.body.position.distanceTo(hero.position)<3.2);return n?{npc:n}:null;}
function interact(){const n=nearby();if(n?.door){if(n.door.target==='cartasCurico'||roomId==='cartasCurico'){rebuild(roomId==='valpo'?'cartasCurico':'valpo');return;}$('message').textContent='Este edificio se abrirá en una próxima etapa de la versión 3D.';}else if(n?.npc)$('message').textContent=n.npc.name+': «Bienvenido. Por aquí las cartas, la aventura y una buena cerveza siempre reúnen a los amigos». Esta conversación es una muestra visual.';else $('message').textContent='Explora Curicó y visita la tienda TCG. Esta versión prueba los gráficos, la caminata y las cámaras; las misiones y los combates llegarán después.';$('dialog').showModal();keys.clear();}
$('close').onclick=()=>$('dialog').close();$('talk').onclick=interact;$('visit').onclick=()=>rebuild(roomId==='valpo'?'cartasCurico':'valpo');$('camera').onclick=()=>{cameraMode=1-cameraMode;$('camera').textContent='Cámara: '+(cameraMode?'aventura':'ciudad');};$('rotate').onclick=()=>angle+=Math.PI/2;$('light').onclick=()=>{phase=(phase+1)%3;setLight();};
const movement={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};
addEventListener('keydown',e=>{if($('dialog').open)return;const key=movement[e.key];if(key){e.preventDefault();keys.add(key);}if(!e.repeat&&e.key.toLowerCase()==='e')interact();if(!e.repeat&&e.key.toLowerCase()==='c')$('camera').click();});addEventListener('keyup',e=>keys.delete(movement[e.key]));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());
for(const button of document.querySelectorAll('[data-move]')){button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);keys.add(button.dataset.move);});for(const type of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(type,()=>keys.delete(button.dataset.move));}
stage.addEventListener('contextmenu',e=>e.preventDefault());function resize(){const width=stage.clientWidth,height=stage.clientHeight;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(Math.min(width,800),Math.min(width,800)*height/width,false);const target=cameraMode?hero.position:new THREE.Vector3(),fit=Math.min(1,camera.aspect),d=cameraMode?14:35/fit;camera.position.set(target.x+Math.sin(angle)*d,cameraMode?11:28/fit,target.z+Math.cos(angle)*d);camera.lookAt(target.x,1,target.z);}addEventListener('resize',resize);
rebuild('valpo');let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;let x=(keys.has('right')?1:0)-(keys.has('left')?1:0),z=(keys.has('down')?1:0)-(keys.has('up')?1:0);if($('dialog').open)x=z=0;const len=Math.hypot(x,z);if(len){x/=len;z/=len;const dx=(x*Math.cos(angle)+z*Math.sin(angle))*dt*4,dz=(-x*Math.sin(angle)+z*Math.cos(angle))*dt*4,old=hero.position.clone();movePlayer(room,data.solid,hero.position,dx,dz);const dist=old.distanceTo(hero.position);if(dist>.001){walk+=dist*5;hero.rotation.y=Math.atan2(dx,dz);hero.position.y=Math.abs(Math.sin(walk))* .06;hero.userData.limbs.forEach((l,i)=>l.rotation.x=Math.sin(walk+(i<2?0:Math.PI))*(i%2?.55:-.4));}}else{hero.position.y=0;hero.userData.limbs.forEach(l=>l.rotation.x*=.8);}const target=cameraMode?hero.position.clone():new THREE.Vector3(0,0,0),distance=cameraMode?14:35/Math.min(1,camera.aspect);camera.position.lerp(new THREE.Vector3(target.x+Math.sin(angle)*distance,target.y+(cameraMode?11:28/Math.min(1,camera.aspect)),target.z+Math.cos(angle)*distance),Math.min(1,dt*7));camera.lookAt(target.x,1,target.z);const n=nearby();$('hint').textContent=n?.door?'E / Hablar: '+(n.door.target==='cartasCurico'?'entrar a la tienda TCG':roomId==='cartasCurico'?'salir a Curicó':'examinar entrada'):n?.npc?'E / Hablar: '+n.npc.name:'Recorre la ciudad · puedes cambiar cámara y hora';renderer.render(scene,camera);}requestAnimationFrame(frame);
}
